# Johnson's $S_U$ Distribution Approximation for Basket/Asian Options

Chenyin Gong, cygong1226@pku.edu.cn

### Table of Contents

- Motivation
- Formulation
    - Moment Matching for The Johnson's $S_u$ Distribution
    - Moments of Basket Option
    - Moments of Asian Option
    - An Example
- Numerical Experiments
    - Results in [krekel et al. (2004)](https://books.google.com/books?hl=zh-CN&lr=&id=KqfXtzqyeXEC&oi=fnd&pg=PA181&ots=6_IeW_A9eK&sig=-6_7dQjToLxDkiZGGUHr8HISTRs#v=onepage&q&f=false)
    - Results in [Milevsky and Posner (1998)](https://ssrn.com/abstract=108539)
- References

## 1 Motivation

By No Arbitrage assumption, the price of derivative security is defined as

\begin{align}
    P & = e^{-rT} \left[ \int_{0}^{\infty} G(x) h(x) dx \right], \tag{1}
\end{align}

where $r$ is the risk-free rate, $T$ is the time-to-expiry, $G(x)$ is the payoff function, $h(x)$ is the state-price density (SPD) and $H(x)$ is the cumulative distribution function (CDF) of $h(x)$.

In the Black-Scholes-Merton model, SPD is easy to obtain (lognormal). However, it is difficult to find a closed-form expression for the SPD of most exotic path-dependent payoffs.

[Milevsky and Posner (1998)](https://ssrn.com/abstract=108539) provide a method (4M) that uses an approximate SPD $\tilde{h}(x)$ from the Jonhson (1949) family to approximate the true SPD $h(x)$ by matching the first four moments such that

\begin{align}
    P & = e^{-rT} \left[ \int_{-\infty}^{\infty} G(x) \tilde{h}(x) dx \right], \tag{2}
\end{align}

where $\tilde{h}(x)$ is "built" so that

\begin{align}
    & \int_{-\infty}^{\infty} x \tilde{h}(x) dx = \mu_x = \int_{0}^{\infty} x h(x) dx, \tag{3} \\
    & \int_{-\infty}^{\infty} (x - \mu_x)^i \tilde{h}(x) dx = \int_{0}^{\infty} (x - \mu_x)^i h(x) dx, \ i = 2, 3, 4. \tag{4}
\end{align}

Note that the Johnson's $S_u$ distribution is the solution of Hyperbolic Normal Stochastic Volatility (NSVh) model ([Choi et al.；2018](https://doi.org/10.1002/fut.21967)) with $\lambda$ = 1 (a parameter in their model), and use the algorithm below to solve the moment matching. Therefore, we can directly use NSVh to implement the 4M method.

## 2 Formulation

### 2.1 Moment Matching for The Johnson's $S_u$ Distribution

The Johnson's $S_u$ distribution is a four-parameter family of probability distributions. It can be formulated as a transformation of the normal distribution:

\begin{align}
    & z = \gamma + \delta \sinh^{-1} \left(\frac {x - \xi} {\lambda} \right), \notag \\
    & \text{where} \ z \sim \mathcal{N}(0, 1). \tag{5}
\end{align}

[Tuenter (2001)](https://doi.org/10.1080/00949650108812126) proposes the following algorithm to determine the parameters of the Johnson's $S_u$ distribution.

Let $y = \frac {x - \xi} {\lambda}$, $w = e^{\delta^{-2}}$, and $\Omega = \frac {\gamma} {\delta}$. The mean, variance and the Pearsonian coefficients of skewness and kurtosis of $y$ are

\begin{align}
    & \mu^y_1 = - w^{1/2} \sinh \Omega, \tag{6} \\
    & \mu^y_2 = \frac {1} {2} \left(w - 1 \right) \left(w \cosh 2 \Omega + 1 \right), \tag{7} \\
    & \beta_1 = \frac {(\mu^y_3)^2} {(\mu^y_2)^3} = \frac {(\mu^x_3)^2} {(\mu^x_2)^3} = \left(w - 1 - m \right)\left(w + 2 + \frac {1} {2} m \right)^2, \label{eq:beta1} \tag{8} \\
    & \beta_2 = \frac {\mu^y_4} {(\mu^y_2)^2} = \frac {\mu^x_4} {(\mu^x_2)^2} = -3 + \left(w^2 + 2w +3 \right) \left(w^2 - \frac {1} {2} m^2 - 2m \right) , \label{eq:beta2} \tag{9}
\end{align}

where the original hyperbolic sine $\sinh \Omega$ is substituted by $t$, and $m = \frac {w^2 - 1} {w + 1 + 2wt^2}$. 

The restriction on $w$ is

\begin{equation}
    \max \{ w_0, w_1 \} < w \leq w_2 = \sqrt {-1 + \sqrt{2 (\beta_2 - 1)}}, \tag{10}
\end{equation}

where $w_0$ is the unique and postive root of $\beta_1 = (w -1)(w + 2)^2$, $w_1$ the unique positive root of $\beta_2 = (w^4 + 2 w^3 + 3w^2 - 3)$, and $w_2$ the unique positive root of $\beta_2 = (w^4 + 2 w^2 + 3)/2$. In addition, $\beta_2 > 3$ for $w_1 < w_2$ to hold.

By \eqref{eq:beta2},

\begin{equation}\label{eq:m}
    m = -2 + \sqrt{4 + 2 \left ( w^2 - \frac {\beta_2 + 3} {w^2 + 2w + 3} \right )}. \tag{11}
\end{equation}

Then subsitute for $m$ in \eqref{eq:beta1}, we obtain an implicit expression for $w$ as the value that satisfies $f(w) = \beta_1$, where

\begin{align}\label{eq:fw}
    f(w) &= \left [w + 1 - \sqrt{4 + 2 \left ( w^2 - \frac {\beta_2 + 3} {w^2 + 2w + 3} \right )} \right ] \left [w + 1 + \frac{1}{2}\sqrt{4 + 2 \left ( w^2 - \frac {\beta_2 + 3} {w^2 + 2w + 3} \right )} \right]. \tag{12}
\end{align}

Eq \eqref{eq:fw} is strictly decreasing so that $f(w) = \beta_1$ can be computed by using a bisection or a Newton-Raphson method.

After $w$ and $m$ are determined, the other parameters can be easily obtained

\begin{align}
    & \Omega = -\text{sign}(\mu_3) \sinh^{-1} \sqrt{\frac {w+1} {2w} \left (\frac {w-1} {m} - 1 \right)}, \tag{13} \\
    & \delta = \frac {1} {\sqrt {\ln w}}, \tag{14} \\
    & \gamma = \frac {\Omega} {\sqrt {\ln w}}, \tag{15} \\
    & \lambda = \frac {\sigma_x} {w - 1} \sqrt{\frac {2m} {w + 1}}, \tag{16} \\
    & \xi = \mu^x_1 - \text{sign}(\mu_3) \frac {\sigma_x} {w - 1} \sqrt {w - 1 - m}, \tag{17} \\
    & \text{where} \ \sigma_x = \sqrt {\mu^x_2 - (\mu^x_1)^2}.
\end{align}

### 2.2 Moments of Basket Option

The price of a basket of stocks is defined as
\begin{equation}
    B(T) = \sum_{i=1}^{n} w_i S_i(T), \tag{18}
\end{equation}
where $S_i(T) \sim F^T_i e^{\sigma_i \sqrt{T} Z_i - T\sigma^2_i/2}$, $z_i \overset{i.i.d.}\sim \mathcal{N}(0, 1)$, $\sum_{i=1}^{n} w_i = 1$, $0 < w_i < 1$, and $F^T_i$ is the T-forward price of stock $i$, $\forall i = 0, \dots, n$.

The first four moments of Basket option are:
\begin{align}
    & E(B(T)) = \sum_{i=1}^{n} w_i F^T_i, \tag{19} \\
    & E(B^2(T)) = \sum_{i, j}^{n} w_i w_j F^T_i F^T_j e^{\sigma_i \sigma_j \rho_{ij} T}, \tag{20} \\
    & E(B^3(T)) = \sum_{i, j, k}^{n} w_i w_j w_k F^T_i F^T_j F^T_k \exp \left\{ \left( \sum_{ a, b \in (i, j, k), \ a \leq b } \sigma_a \sigma_b \rho_{ab} \right) T \right \}, \tag{21} \\
    & E(B^4(T)) = \sum_{i, j, k, l}^{n} w_i w_j w_k w_l F^T_i F^T_j F^T_k F^T_l \exp \left\{ \left( \sum_{ a, b \in (i, j, k, l), \ a \leq b } \sigma_a \sigma_b \rho_{ab} \right) T \right \}, \tag{22} \\
\end{align}

### 2.3 Moments of Asian Option

The formula for Asian option with a log-normal underlying asset is given by

\begin{equation}
    A(T) = \frac {1} {T} \int_{0}^{T} S_T dt, \tag{23}
\end{equation}

where $S_t = S_0 \exp \left \{ (r - \frac{\sigma^2} {2}) t + \sigma W_t \right\}$ follows a geometric Brownian motion.

The moment expression for Asian option can be found in [Geman and Yor (1993)](https://onlinelibrary.wiley.com/doi/abs/10.1111/j.1467-9965.1993.tb00092.x):

\begin{align}
    & E(A^n(T)) = \frac {S^n_0} {T^n} \frac {n!} {\lambda^{2n}} \left \{ \sum_{j=0}^{n} d^{(v/\lambda)}_j \exp \left \{ \left(\frac {\lambda^2 j^2} {2} + \lambda j v\right) t \right \} \right \}, \tag{24} \\
   \text{where} \ & d^{\beta}_j = 2^n \prod_{0 \leq i \neq j \leq n}{ \left [(\beta + j)^2 - (\beta + i )^2 \right]^{-1}}, \ \lambda = \sigma, \ v = \left(r - \sigma^2/2 \right)/\sigma. \notag
\end{align}

### 2.4 An Example

The example is provided in [Milevsky and Posner (1998)](https://ssrn.com/abstract=108539). The No Arbitrage price of a European call, struck at $K$ on the Asian call option $A_T$, is:

\begin{align}
    P &= e^{ -rT } \left[ \int_{K}^{\infty} (x - K) h(x) dx \right], \notag \\
    &= e^{-rT} \left [ F(A_T) - K + \int_{0}^{K} H(x) dx  \right ], \notag \\
    &\cong e^{-rT} \left [ F(A_T) - K + \int_{-\infty}^{K} \tilde{H}(x) dx  \right ]. \tag{25} 
\end{align}

where $F(A_T) = E(A_T) = \int_{0}^{\infty} x h(x) dx$, and $\tilde{H}(x)$ is the CDF of $\tilde{h}(x)$ which can be derived as

\begin{align}
    \int_{-\infty}^{K} \tilde{H}(x) dx &= (K - \xi) \mathcal{N}(Q) + \frac {\lambda} {2} \exp \left \{ \frac {1} {2\delta^2} \right \} \left [ \exp \left \{ \frac {\gamma} {\delta} \right \} \mathcal{N} (Q + \frac{1}{\delta}) - \exp \left \{ \frac {-\gamma} {\delta} \right \} \mathcal{N} (Q - \frac{1}{\delta}) \right ], \tag{26}
\end{align}

where $Q = \gamma + \delta \sinh^{-1} \left(\frac {K - \xi} {\lambda} \right)$.

We can compute the first four moments of $A(T)$ based on the section 2.3, and find the four parameters $\gamma, \ \delta, \ \xi, \ and \ \lambda$ of the Johnson's $S_U$ distribution through section 2.1. Then the price $P$ can be calculated.

## 3  Numerical Experiments

This section reproduces the results in [krekel et al. (2004)](https://books.google.com/books?hl=zh-CN&lr=&id=KqfXtzqyeXEC&oi=fnd&pg=PA181&ots=6_IeW_A9eK&sig=-6_7dQjToLxDkiZGGUHr8HISTRs#v=onepage&q&f=false) and [Milevsky and Posner (1998)](https://ssrn.com/abstract=108539).

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import numpy as np
import pandas as pd

### Uncomment below if you want to run on your own modified code
import sys
sys.path.insert(sys.path.index('')+1, r"E:\PycharmProjects\PyFENG")
import pyfeng as pf

In [3]:
texp = 5
rho = 0.5
o4 = np.ones(4)
sigma = o4 * 0.4
file = 'KrekelEtAl2004-Wilmott-BasketOption.xlsx'

### 3.1 Results in [krekel et al. (2004)](https://books.google.com/books?hl=zh-CN&lr=&id=KqfXtzqyeXEC&oi=fnd&pg=PA181&ots=6_IeW_A9eK&sig=-6_7dQjToLxDkiZGGUHr8HISTRs#v=onepage&q&f=false)

#### Table 1 
#### Changing Correlation

In [4]:
df = pd.read_excel(file, sheet_name='1')
df

Cor  Beisser  Gentle     Ju   Levy  MP-RG  MP-4M  MC-CV  StdDEv    Exact
0  0.10    20.12   15.36  21.77  22.06  20.25  21.36  21.62  0.0319  21.6921
1  0.30    24.21   19.62  25.05  25.17  22.54  24.91  24.97  0.0249  25.0293
2  0.50    27.63   23.78  28.01  28.05  24.50  27.98  27.97  0.0187  28.0074
3  0.70    30.62   27.98  30.74  30.75  26.18  30.74  30.72  0.0123  30.7427
4  0.80    31.99   30.13  32.04  32.04  26.93  32.04  32.03  0.0087  32.0412
5  0.95    33.92   33.41  33.92  33.92  27.97  33.92  33.92  0.0024  33.9187

In [5]:
rhos = [0.1, 0.3, 0.5, 0.7, 0.8, 0.95]
result = np.zeros_like(rhos, dtype=float)
for i in range(len(rhos)):
    r = rhos[i]
    m = pf.BsmBasketJsu(sigma=sigma, cor=rhos[i])
    result[i] = np.round(m.price(100, 100*o4, texp), 2)
np.round(result, 2), np.round(result, 2) - df['MP-4M'].values

(array([21.36, 24.91, 27.98, 30.74, 32.04, 33.92]),
 array([0., 0., 0., 0., 0., 0.]))

#### Table 2
#### Changing Strike

In [6]:
df = pd.read_excel(file, sheet_name='2')
df

K  Beisser  Gentle     Ju   Levy  MP-RG  MP-4M  MC-CV  StdDev    Exact
0    50    54.16   51.99  54.31  54.34  51.93  54.35  54.28  0.0383  54.3102
1    60    47.27   44.43  47.48  47.52  44.41  47.50  47.45  0.0375  47.4811
2    70    41.26   37.93  41.52  41.57  38.01  41.53  41.50  0.0369  41.5225
3    80    36.04   32.40  36.36  36.40  32.68  36.34  36.52  0.0363  36.3518
4    90    31.53   27.73  31.88  31.92  28.22  31.86  31.85  0.0356  31.8768
5   100    27.63   23.78  28.01  28.05  24.50  27.98  27.98  0.0350  28.0074
6   110    24.27   20.46  24.67  24.70  21.39  24.63  24.63  0.0344  24.6605
7   120    21.36   17.65  21.77  21.80  18.77  21.73  21.74  0.0338  21.7626
8   130    18.84   15.27  19.26  19.28  16.57  19.22  19.22  0.0332  19.2493
9   140    16.65   13.25  17.07  17.10  14.70  17.04  17.05  0.0326  17.0655
10  150    14.75   11.53  15.17  15.19  13.10  15.14  15.15  0.0320  15.1640

In [7]:
strike = np.arange(50., 151., 10)
m = pf.BsmBasketJsu(sigma=sigma, cor=0.5)
result = m.price(strike, spot=100*o4, texp=texp)
np.round(result, 2), np.round(result, 2) - df['MP-4M'].values

(array([54.35, 47.5 , 41.53, 36.34, 31.86, 27.98, 24.63, 21.73, 19.22,
        17.04, 15.14]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]))

#### Table 3
#### Changing Forward

In [8]:
df = pd.read_excel(file, sheet_name='3')
df

F  Beisser  Gentle     Ju   Levy  MP-RG  MP-4M  MC-CV  StdDev
0    50     4.16    3.00   4.34   4.34   3.93   4.33   4.34  0.0141
1    60     7.27    5.53   7.51   7.52   6.56   7.50   7.50  0.0185
2    70    11.26    8.91  11.55  11.57   9.95  11.53  11.53  0.0227
3    80    16.04   13.13  16.37  16.40  14.10  16.34  16.35  0.0268
4    90    21.53   18.11  21.89  21.92  18.97  21.86  21.86  0.0309
5   100    27.63   23.78  28.01  28.05  24.50  27.98  27.98  0.0350
6   110    34.27   30.08  34.66  34.70  30.63  34.63  34.63  0.0391
7   120    41.36   36.91  41.75  41.80  37.32  41.73  41.71  0.0433
8   130    48.84   44.21  49.23  49.28  44.49  49.21  49.19  0.0474
9   140    56.65   51.92  57.04  57.10  52.08  57.03  57.00  0.0516
10  150    64.75   59.98  65.13  65.19  60.05  65.14  65.08  0.0556

In [9]:
spot = np.arange(50., 151., 10)[:,None]*np.ones(4)
result = np.zeros_like(spot[:, 0], dtype=float)
for i in range(len(spot[:, 0])):
    m = pf.BsmBasketJsu(sigma=sigma, cor = 0.5)
    result[i] = np.round(m.price(100, spot[i], texp), 2)
np.round(result, 2), np.round(result, 2) - df['MP-4M'].values

(array([ 4.33,  7.5 , 11.53, 16.34, 21.86, 27.98, 34.63, 41.73, 49.21,
        57.03, 65.14]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]))

#### Table 4
#### Changing all volatilities

In [10]:
df = pd.read_excel(file, sheet_name='4')
df

Sigma  Beisser  Gentle     Ju   Levy  MP-RG  MP-4M  MC-CV  StdDev    Exact
0    0.05     3.53    3.52   3.53   3.53   3.52   3.53   3.53  0.0014   3.5259
1    0.10     7.04    6.98   7.05   7.05   6.99   7.05   7.05  0.0042   7.0498
2    0.15    10.55   10.33  10.57  10.57  10.36  10.57  10.57  0.0073  10.5696
3    0.20    14.03   13.52  14.08  14.08  13.59  14.08  14.08  0.0115  14.0830
4    0.30    20.91   19.22  21.08  21.09  19.49  21.07  21.07  0.0237  21.0787
5    0.40    27.63   23.78  28.01  28.05  24.50  27.98  27.98  0.0350  28.0074
6    0.50    34.15   27.01  34.84  34.96  28.51  34.73  34.80  0.0448  34.8289
7    0.60    40.41   28.84  41.52  41.78  31.56  41.19  41.44  0.0327  41.4931
8    0.70    46.39   29.30  47.97  48.50  33.72  46.23  47.86  0.0490  47.9430
9    0.80    52.05   28.57  54.09  55.05  35.15  48.39  54.01  0.0685  54.1192
10   1.00    62.32   24.41  64.93  67.24  36.45  47.90  65.31  0.0996  65.4256

In [11]:
sigmas = np.array([5, 10, 15, 20, 30, 40, 50, 60, 70, 80, 100])/100
result = np.zeros_like(sigmas, dtype=float)
for i in range(len(sigmas)):
    m = pf.BsmBasketJsu(sigma=sigmas[i]*o4, cor=0.5)
    result[i] = np.round(m.price(100, 100*o4, texp), 2)
np.round(result, 2), np.round(result, 2) - df['MP-4M'].values

(array([ 3.53,  7.05, 10.57, 14.08, 21.07, 27.98, 34.73, 41.19, 46.23,
        48.39, 47.9 ]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]))

#### Table 5
#### Changing the other volatilities with $\sigma_1=1$

In [12]:
df = pd.read_excel(file, sheet_name='5')
df

Sigma  Beisser  Gentle     Ju   Levy  MP-RG  MP-4M  MC-CV  StdDev    Exact
0    0.05    19.45   15.15  35.59  55.56  35.22  18.51  22.65  0.5594  19.4591
1    0.10    20.84   16.60  36.19  55.52  35.23  18.64  21.30  0.3858  20.9682
2    0.15    22.60   18.08  36.93  55.61  35.24  18.81  22.94  0.2660  23.0042
3    0.20    24.69   19.56  37.80  55.71  35.26  19.01  25.24  0.2124  25.3794
4    0.30    29.52   22.35  39.97  55.98  35.30  19.42  30.95  0.1603  30.6027
5    0.40    34.72   24.73  42.66  56.35  35.36  20.37  36.89  0.1156  36.0485
6    0.50    39.96   26.52  45.84  56.89  35.44  20.60  41.72  0.0894  41.4943
7    0.60    45.05   27.59  49.39  57.68  35.56  21.72  46.68  0.0472  46.8189
8    0.70    49.88   27.87  53.21  58.87  35.72  23.66  51.78  0.0587  51.9361
9    0.80    54.39   27.38  57.17  60.70  35.93  27.38  56.61  0.0742  56.7772
10   1.00    62.32   24.41  64.93  67.24  36.45  47.90  65.31  0.0996  65.4256

In [13]:
sigmas = np.array([5, 10, 15, 20, 30, 40, 50, 60, 70, 80, 100])/100
result = np.zeros_like(sigmas, dtype=float)
for i in range(len(sigmas)):
    sigma_asym = np.array([sigmas[i], sigmas[i], sigmas[i], 1.0])
    m = pf.BsmBasketJsu(sigma=sigma_asym, cor=0.5)
    result[i] = np.round(m.price(100, 100*o4, texp), 2)
np.round(result, 2), np.round(result, 2) - df['MP-4M'].values

(array([18.64, 18.78, 18.92, 19.07, 19.42, 19.9 , 20.6 , 21.72, 23.66,
        27.38, 47.9 ]),
 array([ 0.13,  0.14,  0.11,  0.06,  0.  , -0.47,  0.  ,  0.  ,  0.  ,
         0.  ,  0.  ]))

### 3.2 Results in [Milevsky and Posner (1998)](https://ssrn.com/abstract=108539)

#### Table 1
#### Continuous Averaging

In [14]:
df = pd.read_excel(file, sheet_name='6')
df

r  sigma  q  T  K  F  Monte Carlo  MC error    G&E     RG     4M
0  0.18    0.3  0  1  2  2        0.217    0.0014  0.227  0.217  0.218
1  0.05    0.5  0  2  2  2        0.347    0.0020  0.351  0.347  0.349

In [15]:
result = []
m = pf.BsmAsianJsu(sigma=0.3, intr=0.18, divr=0.0)
result.append(np.round(m.price(2.0, 2.0, 1.0), 3))

m = pf.BsmAsianJsu(sigma=0.5, intr=0.05, divr=0.0)
result.append(np.round(m.price(2.0, 2.0, 2.0), 3))
np.round(result, 3), np.round(result, 3) - df['4M'].values

(array([0.218, 0.349]), array([0., 0.]))

## References

[1] Choi, J., Liu, C., & Seo, B. K. (2019). Hyperbolic normal stochastic volatility model. Journal of Futures Markets, 39(2), 186-204.

[2] Geman, H., & Yor, M. (1993). Bessel processes, Asian options, and perpetuities. Mathematical finance, 3(4), 349-375.

[3] Krekel, M., de Kock, J., Korn, R., & Man, T. K. (2006). An analysis of pricing methods for basket options. The Best of Wilmott, 2, 181-188.

[4] Posner, S. E., & Milevsky, M. A. (1998). Valuing exotic options by approximating the SPD with higher moments. The Journal of Financial Engineering, 7(2).

[5] Tuenter, H. J. (2001). An algorithm to determine the parameters of SU-curves in the Johnson system of probabillity distributions by moment matching. Journal of Statistical Computation and Simulation, 70(4), 325-347.